# Generated by Django 4.0.1 on 2022-01-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, db_column='DS_TITLE', max_length=100, null=True)),
                ('book_author', models.CharField(blank=True, db_column='DS_AUTHOR', max_length=100, null=True)),
                ('book_price', models.DecimalField(db_column='NR_PRICE', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Livros',
            },
        ),
    ]
